CREATE TABLE [dbo].[Producto]
(
ProductoId INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_Producto
PRIMARY KEY CLUSTERED (ProductoId)
, Descripcion VARCHAR(250) NOT NULL
, Estado BIT NOT NULL
)
WITH (DATA_COMPRESSION=PAGE)
GO